name: Periodic health check

on:
  schedule:
    - cron:  '0/5 * * * *'
  push:
    branches:
      - Periodic-health-check

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://pacific-everglades-48882.herokuapp.com/version
        follow-redirect: no